Add Mutation.deleteProduct
CodeRandomware/graphql-demo pull request #14
Opened 2022-03-04 13:39 UTC by marshalWilliam

- Implemented Delete Product Mutation
- Added Unit Test for Mutation.deleteProduct

2022-03-05 02:14 UTC, ccpacillos requested changes

2022-03-05 02:14 UTC, ccpacillos commented on src/schemas/functions/delete.ts
> +    if (product.owner == userID) {
Use `Buffer.compare()` to compare Buffer values.

2022-03-06 16:36 UTC, marshalWilliam reviewed
Also used `Buffer.compare` for Mutation.updateProduct function

2022-03-07 00:02 UTC, ccpacillos requested changes

2022-03-07 00:02 UTC, ccpacillos commented on src/schemas/functions/put.ts
> +    if (!Buffer.compare(product.owner, userID)) {
It's preferred to use `Buffer.compare(product.owner, userID) === 0`.

2022-03-07 01:39 UTC, ccpacillos approved these changes

2022-03-07 10:46 UTC, merged